refactor: refactor form validation
ecomfe/veui pull request #1003
Opened 2022-02-25 10:26 UTC by xiaodemen

2022-03-03 03:27 UTC, xiaodemen commented
### 功能更新点

- [ ] 支持 form 级别上配置紧凑的消息展示布局，prop 暂定 `validityDisplay` or `messageDisplay`
- [ ] form 的 default scopedSlot 新增了 `validities`
- [ ] `field` 支持多种状态的消息，见`Message.type`。
- [ ] `field` 默认显示多条消息，TODO：支持全局配置，排序
- [ ] 支持消息文案前有 icon， TODO：如何配置？
- [ ] 交互时异步校验，显示 loading 的状态， TODO：input invalid 状态先去掉
- [ ] 支持 abstract field，表示没有布局（无label，无margin）且不显示验证消息，自动向上透传至 non-abstract ancestor field。
- [ ] fieldset 的下级 field 自动认为是 abstract 的，故错误信息自动交由 fieldset 显示。
- [ ] field 支持 withholdValidity，不再自动给内部的 input 绑定事件和自动继承 invalid，交由 default scopedSlot 中用户手动处理
- [ ] field 开始感知下级 primaryInput（多个则取 input name 和 field name 一致的那个） 的内置校验错误，内置错误会阻止表单提交。
- [ ] 支持自定义消息渲染，配置 `Message.render` ??
- [ ] `Message` 组件

### 技术更新点

```ts
type Validity = {
  type: 'error' | 'warning' | 'success',
  message?: string,
  render?: Function  // 带确定
}
```

- [ ] `useRule` 实现 rule 校验
- [ ] `useValidator` 实现 validator 校验
- [ ] `useValidity` 实现验证消息的获取与更新

### 潜在的问题
- `form.validate` 的返回值，每个字段的验证信息都变成数组
- form.reset和 hideValidity 的需求？
- beforeValidate/afterValidate 的 this 变成 undefined

2022-03-18 05:11 UTC, Justineo requested changes

2022-03-18 05:11 UTC, Justineo commented on packages/veui/src/components/Loading.vue
> +<div
这个 transition 应该是给 Table 切换 loading 的时候用的，是不是在那边补一下

2022-03-18 05:11 UTC, Justineo commented on packages/veui/src/locale/en-US/Field.js
> +    validating: 'validating...'
```suggestion
    validating: 'Validating...'
```

2022-03-18 05:11 UTC, Justineo commented on packages/veui/src/locale/zh-Hans/Field.js
> +    validating: '校验中...'
```suggestion
    validating: '校验中……'
```

2022-03-18 05:11 UTC, Justineo commented on packages/veui/src/mixins/input.js
> +      (vm) => vm.isTopMostInput && vm.field.addInput(vm.getFacade())
不要用 expression，展开成 if 吧

2022-03-18 05:11 UTC, Justineo commented on packages/veui/src/utils/context.js
> +export function bindVm (targets, vm) {
写个注释吧，作用是啥

2022-03-18 05:11 UTC, Justineo commented on packages/veui/src/utils/helper.js
> +export function resolveInterpolation (message, data, compat) {
renderTpl？

2022-03-22 03:40 UTC, xiaodemen commented on packages/veui/src/components/Input.vue
> +        }
Input 内置校验逻辑可能是主动触发的，只有提交校验时是 Field 来调用 input.validate

2022-03-25 03:31 UTC, Justineo approved these changes

2022-03-25 03:31 UTC, merged