feat: add select-all for select
ecomfe/veui pull request #1008
Opened 2022-03-04 03:00 UTC by xiaodemen

2022-03-04 09:21 UTC, Justineo requested changes

2022-03-04 09:21 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +      this.SELECT_ALL_SYMBOL = this.SELECT_ALL_SYMBOL || Symbol('select_all')
computed 里面不要赋值吧，这个直接放到 module scope 下面就好了

2022-03-04 09:21 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +    },
这两个和计算 `leafOptionInfo` 的可以放一起吧，一次循环应该都能得到了。感觉直接放在 `selectAllData` 里面就好了。

2022-03-04 09:21 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +      let canUncheck = []
selectable / deselectable?

2022-03-04 09:21 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +    isOptionSelected (value) {
`isSelected (value)` 就已经明确了吧

2022-03-07 02:28 UTC, Justineo requested changes

2022-03-07 02:28 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +              isSelecteAllOption ? this.isAllSelected : !!option.selected
this.selectAllData.xxx

2022-03-07 02:28 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +              isSelecteAllOption ? this.isSelectAllIndeterminate : false
this.selectAllData.xxx

2022-03-15 03:49 UTC, Justineo requested changes

2022-03-15 03:49 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +    },
```suggestion
    composition: Boolean,
```

这里还是默认关了吧，这个 breaking 感觉应该问题不大

2022-03-15 03:49 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +      // this.t('selectAll')
```suggestion
```

2022-03-15 03:49 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +        // checked={!!option.selected} 这里有问题，待排查
这里还有问题吗？

2022-03-15 06:24 UTC, xiaodemen commented on packages/veui/src/components/Select/Select.vue
> +        // checked={!!option.selected} 这里有问题，待排查
> 这里还有问题吗？

现在测试过没问题

2022-03-15 06:29 UTC, Justineo commented on packages/veui/src/components/Select/Select.vue
> +        // checked={!!option.selected} 这里有问题，待排查
没问题就删了吧，可以 rebase 一下，squash 一下 apply code suggestion 的 commit

2022-03-18 12:13 UTC, merged