The 'alert' and 'confirm' of plugins support modifying the footer button label
ecomfe/veui pull request #1119
Opened 2023-01-10 11:36 UTC by myth929

1. support 'okLabel' in $alert;
2. support 'okLabel' and 'cancelLabel' in $confirm.

2023-01-10 12:28 UTC, Justineo commented
👍

是否可以同时更新 `managers/prompt` 并且更新一下 test case（`packages/veui/test/unit/specs/managers/{alert,confirm,prompt}.spec.js`）？

2023-01-10 12:39 UTC, myth929 commented
> 👍
> 
> 是否可以同时更新 `managers/prompt` 并且更新一下 test case（`packages/veui/test/unit/specs/managers/{alert,confirm,prompt}.spec.js`）？

好的

2023-01-12 15:58 UTC, Justineo requested changes
Support for `prompt` and test cases required

2023-01-17 16:48 UTC, Justineo commented on .gitignore
> +.history/
```suggestion
```

2023-01-17 16:49 UTC, merged