fix: fix input style for checkbox
ecomfe/veui pull request #1127
Opened 2023-02-10 06:38 UTC by xiaodemen

2023-02-10 06:48 UTC, Justineo requested changes

2023-02-10 06:48 UTC, Justineo commented on packages/veui-theme-dls/components/checkbox.less
> +  & &-input {
Why not `&-input`?

2023-02-10 07:02 UTC, xiaodemen commented on packages/veui-theme-dls/components/checkbox.less
> +  & &-input {
选择器权重不变?

2023-02-10 08:14 UTC, Justineo requested changes

2023-02-10 08:14 UTC, Justineo commented on packages/veui-theme-dls/components/checkbox.less
> +  & &-input {
这个不影响吧……

2023-02-13 02:54 UTC, Justineo approved these changes

2023-02-13 02:54 UTC, merged