test: add plugins and partial mixins unit test
ecomfe/veui pull request #746
Opened 2020-11-17 16:36 UTC by Phinome

detail:
- add test of plugins
- add partial test of mixins
- update eslint to fix unit test

#433

2020-11-17 23:43 UTC, Justineo requested changes

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/mixins/activatable.spec.js
> +    expect(vm.activate).to.be.a('undefined')
这里 expect 的东西和描述不一样，这个 `activatable` 主要是来保证用了这个 mixin 的组件对外提供了一个 `activate` 方法，如果没有提供的话会有一个 console 报错。

这里可以用 sinon + sinon-chai 来监控一下 `Vue.util.warn`（底层调用了这个方法）是否被调用了。

Refs:

- https://sinonjs.org/
- https://www.chaijs.com/plugins/sinon-chai/

---

另外，在 `packages/veui` 里运行 `npm install` 以后需要回到根目录再运行一下 `npx lerna bootstrap` 以保证软链可以正常工作。

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/mixins/dropdown.spec.js
> +    /* eslint-disable no-unused-expressions */
```suggestion
```

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/mixins/dropdown.spec.js
> +    /* eslint-disable no-unused-expressions */
```suggestion
```

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/mixins/dropdown.spec.js
> +    /* eslint-disable no-unused-expressions */
```suggestion
```

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/mixins/dropdown.spec.js
> +  it('should not expand dropdown', async () => {
```suggestion
  it('should not expand dropdown when being readonly or disabled', async () => {
```

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/plugins/alert.spec.js
> +  it('should add `alert` methods to Vue prototype', () => {
```suggestion
  it('should add `alert` methods to Vue prototype', () => {
    expect(localVue.prototype.$alert).to.be.a('function')
```

`$alert` 本身也是个 function

2020-11-17 23:43 UTC, Justineo commented on packages/veui/test/unit/specs/plugins/toast.spec.js
> +  it('should add `toast` methods to Vue prototype', () => {
```suggestion
  it('should add `toast` methods to Vue prototype', () => {
    expect(localVue.prototype.$toast).to.be.a('function')
```

2020-11-18 01:42 UTC, Phinome commented on packages/veui/test/unit/specs/mixins/activatable.spec.js
> +    expect(vm.activate).to.be.a('undefined')
学习了，原来如此~不过，Vue-test-util 有一点不太友好，createLocalVue 仅支持传入 `errorHandler`，要是支持 `warnHandler` 就完美了。

2020-11-18 04:22 UTC, Phinome commented on packages/veui/test/unit/specs/mixins/activatable.spec.js
> +    expect(vm.activate).to.be.a('undefined')
换了个思路来解决这个问题。既然最后都是调用 `Vue.util.warn` 这个方法，因此，在运行每次测试 case 前，将 `Vue.config.warnHandler` 这个方法重写一次，给断言提供判断依据，然后单个测试用例执行完毕后，将之清除，恢复为初始状态。

2020-11-18 04:29 UTC, Justineo commented on packages/veui/test/unit/specs/mixins/activatable.spec.js
> +    expect(msg).to.be.undefined
还是不要这么写了，为了这个还要再引 ESLint 插件……

```suggestion
    expect(msg).to.equal(undefined)
```

2020-11-18 05:18 UTC, Phinome commented on packages/veui/test/unit/specs/mixins/activatable.spec.js
> +    expect(msg).to.be.undefined
好

2020-11-19 08:04 UTC, Justineo commented
@Phinome 如果 ready to merge 了，需要改一下 PR 状态，现在是 Draft。

2020-11-19 10:22 UTC, merged