feat: add popover to head of table component
ecomfe/veui pull request #749
Opened 2020-11-19 14:01 UTC by Phinome

it add prop of desc for column, that support popover at head of table component

Referenc: #748

2020-11-20 02:28 UTC, Justineo commented
按现在的设计，Popover 应该是 target 到整个表头单元格外面的，需要修改一下。

![image](https://user-images.githubusercontent.com/1726061/99750276-0d2b8780-2b1b-11eb-8d61-b6ff33b3c6f8.png)

触发区域可能要想办法去掉红色的部分：

![image](https://user-images.githubusercontent.com/1726061/99750313-1caad080-2b1b-11eb-9883-fbff0a57855b.png)

2020-11-20 10:50 UTC, Phinome commented
就目前的现状而言，也就是`popover` 触发过滤掉表头节点中含有操作 `icon` 节点。

2020-11-20 11:14 UTC, Justineo commented
> 就目前的现状而言，也就是`popover` 触发过滤掉表头节点中含有操作 `icon` 节点。

并不是，只过滤可以操作的部分，目前来说只有排序。（筛选的逻辑还没有加）

2020-11-25 03:27 UTC, Justineo requested changes

2020-11-25 03:27 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +      }
直觉上里面可以被 focus 的元素就不应该出 Popover。可以在用 `utils/dom` 模块增加一个 `isFocusable` 函数：

```js
export function isFocusable (elem) {
  return matches(elem, FOCUSABLE_SELECTOR) && !matches(elem, '[tabindex="-1"]')
}
```

2020-11-25 03:55 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +      }
又看了下，可以把 `getFocusable` 实现里面的条件抽出来变成 `isFocusable` 就行了。

2020-11-25 04:10 UTC, Justineo requested changes

2020-11-25 04:10 UTC, Justineo commented on packages/veui/src/utils/dom.js
> +  return matches(elem, FOCUSABLE_SELECTOR) && !matches(elem, '[tabindex="-1"]')
看下上面新增的评论

2020-11-25 04:10 UTC, Justineo commented on packages/veui/src/components/Table/Column.vue
> +      renderPopover: () => {
renderDesc 吧，Popover 是实现细节

2020-11-25 04:10 UTC, Justineo commented on packages/veui/src/components/Table/Column.vue
> +        const render = () => this.$slots.desc || this.desc
应该可以是一个 scoped slot 的，我举个例子，比如内容里面有一个“知道了”，点击以后关闭 Popover，这个时候使用者可以这样扩展：

```vue
<template #desc="{ close }">
  <p>一段说明文本……</p>
  <p><veui-button @click="close">知道了</veui-button></p>
</template>
```

2020-11-25 04:35 UTC, Justineo requested changes

2020-11-25 04:35 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +import { isFocusable } from '@/utils/dom'
```suggestion
import { isFocusable } from '../../utils/dom'
```

VEUI 会和业务代码一起 build，这个 `@` 的配置和业务代码不一样的。

2020-11-25 07:33 UTC, Phinome commented on packages/veui/src/components/Table/_TableHead.js
> +      }
这两个判断不太一致，getFocusable 里的判断之前已经过滤掉非 focusable 的元素了，而在事件处理函数中，传入的的是当前元素，并不知道是否是可以 focusable 的元素。

2020-11-25 08:16 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +      }
我是说把 `getFocusable` 里 `filter` 每一个 `elem` 的逻辑抽出来。

2020-11-26 06:08 UTC, Justineo requested changes

2020-11-26 06:08 UTC, Justineo commented on packages/veui/src/components/Table/Column.vue
> +      }
这两个 method 应该可以删掉。

2020-11-26 06:08 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +      }
```suggestion
      if (!isFocusable(e.target)) {
        this.$set(this.openMap, id, false)
      }
```

1. `e.target` 不可能没有吧。
2. `true` 的情况根本不需要设置吧。

2020-11-26 06:08 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +            {row.map((col, i) => {
```suggestion
            {row.map((col) => {
```

2020-11-26 06:08 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
>                let isLeaf = col.columns.length === 0
```suggestion
              let isLeaf = col.columns.length === 0
              let desc = renderSlot(this, 'desc', {
                close: () => this.openMap[col.id] = false
              }) || this.desc
```

2020-11-26 06:08 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +                  {col.hasDesc() ? (
```suggestion
                  {desc ? (
```

2020-11-26 06:08 UTC, Justineo commented on packages/veui/src/components/Table/_TableHead.js
> +                      })}
```suggestion
                      {desc}
```

2020-11-27 02:53 UTC, merged