fix: fix Uploader extensions prop is invalid
ecomfe/veui pull request #754
Opened 2020-12-02 07:41 UTC by poppyLuo

fix extensions属性校验错误

2020-12-02 08:30 UTC, Justineo requested changes
更新一下 CHANGELOG.md

2020-12-02 08:30 UTC, Justineo commented on packages/veui/src/components/Uploader.vue
>        default () {
所以这里其实不需要 default 吧？

2020-12-02 10:18 UTC, poppyLuo commented on packages/veui/src/components/Uploader.vue
>        default () {
还是先支持一下extensions，有业务组是要同时设置accept和extensions,类似 accept="image/*", extensions=['jpg', 'png']

2020-12-02 12:00 UTC, Justineo commented on packages/veui/src/components/Uploader.vue
>        default () {
我想了一下，有 `extensions` 的情况下应该以 `extensions` 为准，因为之前是依靠它来兜底的，如果设置了，那应该是最精确的表达。你给的这个例子，应该把 `accept` 更新为 `.jpg, .png`。

2020-12-03 02:15 UTC, 599316527 commented on packages/veui/src/components/Uploader.vue
>        default () {
> 有业务组是要同时设置accept和extensions,类似 accept="image/*", extensions=['jpg', 'png']
这个场景应该是不合理的，调起的文件选择框内可选，但是选完了又说格式不支持，显然不合理。

> 有 extensions 的情况下应该以 extensions 为准
支持。除了兼容IE9的情况，accept 从 extensions 生成就行了

2020-12-04 07:20 UTC, Justineo approved these changes

2020-12-04 07:21 UTC, merged