refactor: simplify Uploader.vue by splitting different views into child components and purify implementations of upload
ecomfe/veui pull request #774
Opened 2021-01-13 12:23 UTC by 599316527

* [x] Controls as component
* [ ] FileItem, MediaItem for List
* [ ] Upload implementations without UI dependencies

2021-01-20 14:30 UTC, 599316527 commented on packages/veui/src/mixins/upload.js
> +}
试了，inject 的 object 里面的 field 也没法 reactive

2021-01-20 14:31 UTC, 599316527 commented on packages/veui/src/components/Uploader/_FileUploader.vue
> +            v-if="file.status === 'uploading'"
哦哦 是的 这里是搞 UploaderFile 之前拆的，还没改到

2021-01-20 14:34 UTC, 599316527 commented on packages/veui/src/components/Uploader/Uploader.vue
> +    @custom="handleImageCustomEvent"
感觉还是得有，对于动作有个明确的主体
叫 Item 更合适，代表了 file, image, video, media

2021-01-20 14:35 UTC, 599316527 commented on packages/veui/src/components/Uploader/Uploader.vue
> +    :addable="!canNotAddImage"
也是直接复用原来的computed逻辑，还没改

2021-01-21 01:41 UTC, Justineo commented on packages/veui/src/components/Uploader/Uploader.vue
> +    @custom="handleImageCustomEvent"
ok

2021-01-21 09:10 UTC, 599316527 commented on packages/veui/src/components/Uploader/Uploader.vue
> +  }
正常逻辑的话应该是：

```js
    upload (options, callbacks) {
        const uploadRequest = getUploadRequest(options)
```

但这样每次 upload 都会创建一个函数出来。而这个函数其实只跟 props 里面的那些上传参数有关，写成 computed:uploadRequest 就可以利用 vue 机制来缓存上传函数，只有 props 变化时才更新

另外，把上传、取消上传的实现封装在 UploaderFile 里面，这样在 Vue 里面就只用负责视图逻辑

2021-01-26 07:17 UTC, Justineo requested changes

2021-01-26 10:55 UTC, Justineo approved these changes

2021-01-26 10:56 UTC, Justineo commented
💯

2021-01-26 10:56 UTC, merged