feat: expose match & filter props for searchable and config with config-provider
ecomfe/veui pull request #886
Opened 2021-09-08 11:04 UTC by xiaodemen

2021-09-08 11:48 UTC, Justineo requested changes

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/mixins/searchable.js
> +    warn(`[VEUI searchable] ${e.message}`)
```suggestion
    warn(`[veui-searchable] ${e.message}`)
```

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/mixins/searchable.js
>    keyword = literal ? String(keyword).replace(metaRE, '\\$&') : keyword
可以用 Lodash 的 `escapeRegExp`。

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/mixins/config.js
> +  // 不用 lodash：target 不是数组时不要当成对象的map
```suggestion
  // 不用 _.map 的原因是 target 不是数组时不要当成对象的 map
```

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/managers/context.js
> +            return defaults({}, this.value, parentContextValue) // 每层 provider 都会和上一层的值合并
这里为啥改了

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/mixins/searchable.js
> +    // BREAK: match/filter 的第三个参数统一变成 options
这个写在代码里干啥，写到 changelog 去吧

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/mixins/searchable.js
> +    mixins: [useConfig('searchable_mixin_config', CONFIG_NAMESPACE)],
key 定义一个 const？

2021-09-08 11:48 UTC, Justineo commented on packages/veui/src/mixins/searchable.js
> +  }
这个好像也没有用到？感觉也不需要

2021-09-08 12:34 UTC, xiaodemen commented on packages/veui/src/managers/context.js
> +            return defaults({}, this.value, parentContextValue) // 每层 provider 都会和上一层的值合并
context 里面传递 `undefined` 可以让默认值/更外部的值生效

2021-09-10 07:25 UTC, Justineo requested changes

2021-09-13 10:21 UTC, Justineo requested changes

2021-09-13 10:21 UTC, Justineo commented on CHANGELOG.md
> +  - `match` 函数签名：`(item, keyword, { ancestors }) => boolean | Array<[start, end]>` 以支持自定义高亮逻辑，其中 `[start, end)` 定义高亮范围
```suggestion
  - `match` 函数签名：`(item, keyword, { ancestors }) => boolean | Array<[start, end]>` 以支持自定义高亮逻辑，其中 `[start, end]` 定义高亮范围；
```

2021-09-13 10:21 UTC, Justineo commented on CHANGELOG.md
> +  - `filter` 函数签名：`(item, keyword, { ancestors, offsets }) => boolean` 以支持自定义搜索命中逻辑
```suggestion
  - `filter` 函数签名：`(item, keyword, { ancestors, offsets }) => boolean` 以支持自定义搜索命中逻辑。
```

2021-09-13 10:21 UTC, Justineo commented on CHANGELOG.md
> +- [-] 组件 `Autocomplete` 的 `match` prop 参数签名从 `(item, keyword, ancestors)` 改成 `(item, keyword, { ancestors })`。
```suggestion
- [-] 组件 `Autocomplete` 的 `match` prop 参数签名从 `(item, keyword, ancestors)` 变更为 `(item, keyword, { ancestors })`。
```

2021-09-13 10:21 UTC, Justineo commented on CHANGELOG.md
> +- [+] 为可搜索的组件 `Autocomplete`/`Cascader`/`SearchBox`/`Select`/`Dropdown` 新增 props `match`/`filter`。
```suggestion
- [+] 为可搜索的组件 `Autocomplete`/`Cascader`/`SearchBox`/`Select`/`Dropdown` 新增 `match`/`filter` prop。
```

2021-09-13 11:17 UTC, Justineo approved these changes

2021-09-13 11:19 UTC, merged